version: "3.1"
services:
  web:
    image: nginx:latest
    ports:
      - "40404:80"
    volumes:
      - ./:/var/www
      - ./docker/web/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - backend
  php:
    container_name: tulia-docs_php
    build:
      context: ./docker/web
    volumes:
      - ./:/var/www
    networks:
      - backend
networks:
  backend:
