homepage:
    path: /
    controller: Tulia\Docs\Controller\IndexController::localeRedirect

homepage.localized:
    path: /{_locale}/
    controller: Tulia\Docs\Controller\IndexController::index
    requirements:
        _locale: en|pl

page:
    path: /{_locale}/{page}.html
    controller: Tulia\Docs\Controller\PageController::page
    requirements:
        _locale: en|pl
        page: '.*'
